# Generated by Django 4.0.2 on 2022-07-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_product_digital_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categories'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.items'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
