# Generated by Django 4.0.2 on 2022-07-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_order_customer_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
            ],
        ),
    ]
